background {
    monitor =
    color = rgba(1e1e2eff)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba(89b4faff)
    inner_color = rgba(1e1e2eff)
    font_color = rgba(cdd6f4ff)
    placeholder_text = <i>Password</i>
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    color = rgba(cdd6f4ff)
    halign = center
    valign = center
    position = 0, 100
}
