["powerlevel10k"]
	type = "git-repo"
	url = "https://github.com/romkatv/powerlevel10k.git"
	refreshPeriod = "168h"
[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/NvChad/starter"
  refreshPeriod = "168h"
