#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/.local/share/chezmoi -name .git -prune -o -type f -print | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

nvim $selected
